FROM node:26.3.0 AS build

WORKDIR /app
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Indiquer à Puppeteer où trouver le binaire au runtime
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

## Injection des versions
COPY ./app.module.version /app


COPY ./ora-frontend .
RUN rm -f /app/package-lock.json
RUN npm install

COPY ./deployment-configuration/backend/generate-env.sh /
RUN chmod u+x /generate-env.sh

ENV TZ=Europe/Paris
RUN apt-get update && apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 5173