FROM keycloak/keycloak:24.0

USER root

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./keycloak/patchs-roles.sh /opt/keycloak/data/
RUN chmod +x /opt/keycloak/data/patchs-roles.sh

