FROM debian:bookworm-20240311

ENV TZ=Europe/Paris
RUN apt-get update && apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir /timemachine
RUN chmod 755 /timemachine

RUN apt-get update && apt-get install -y cron postgresql-client

RUN apt-get install -y python3-full python3-pip
RUN apt-get install -y python3-boto3

ADD ./deployment-configuration/timemachine/timemachine.sh /
ADD ./deployment-configuration/timemachine/upload-dump-database-s3.py /
RUN chmod u+x /upload-dump-database-s3.py

RUN chmod +x /timemachine.sh


RUN apt-get update
RUN apt-get install -y curl
RUN curl https://dl.min.io/client/mc/release/linux-arm64/mc \
  --create-dirs \
  -o ~/minio-binaries/mc
RUN apt-get install -y s3cmd

# Toutes les 6 heures
# RUN echo "0 */6 * * * /etc/cron.daily/timemachine.sh" > /etc/crontab

RUN echo "0 */3 * * * root . /etc/environment; /bin/bash /timemachine.sh >> /var/log/crontab.logs" > /etc/crontab



CMD ["cron", "-f"]
