DROP TABLE role IF EXISTS CASCADE;
DROP TABLE namespaces IF EXISTS CASCADE;
DROP TABLE categorie IF EXISTS CASCADE;
DROP TABLE privilege IF EXISTS CASCADE;
DROP TABLE privilege_role_linker IF EXISTS CASCADE;
DROP TABLE role_user_linker IF EXISTS CASCADE;